Repository sdpython/onnx-extended, pull requests merged in 2023-04, with the labels that each got.

#4 Adds a function to measure AVX instructions
  _doc/examples/plot_bench_cpu_vector_sum_avx_parallel.py
  _doc/tutorial/index.rst
  _unittests/ut_validation/test_vector_sum.py
  cmake/CMakeLists.txt
  onnx_extended/validation/_validation.cpp
  onnx_extended/validation/vector_sum.cpp
  onnx_extended/validation/vector_sum.h
Labels: validation

#1 Adds C implementation for TreeEnsemble
  _doc/api/reference.rst
  _doc/examples/plot_conv.py
  _doc/tutorial/index.rst
  _doc/tutorial/usefulcmd.rst
  _unittests/ut_reference/test_backend_c_reference_evaluator.py
  _unittests/ut_reference/test_c_reference_evaluator.py
  _unittests/ut_reference/test_c_tree_ensemble.py
  clang_format.sh
  cmake/CMakeLists.txt
  onnx_extended/ext_test_case.py
  onnx_extended/reference/c_ops/_op_classifier_common.py
  onnx_extended/reference/c_ops/c_op_common.cpp
  onnx_extended/reference/c_ops/c_op_common.h
  onnx_extended/reference/c_ops/c_op_common_parallel.hpp
  onnx_extended/reference/c_ops/c_op_conv_common.h
  onnx_extended/reference/c_ops/c_op_tree_ensemble_classifier.py
  onnx_extended/reference/c_ops/c_op_tree_ensemble_common_.hpp
  onnx_extended/reference/c_ops/c_op_tree_ensemble_common_agg_.hpp
  onnx_extended/reference/c_ops/c_op_tree_ensemble_common_classifier_.hpp
  onnx_extended/reference/c_ops/c_op_tree_ensemble_py_.cpp
  onnx_extended/reference/c_ops/c_op_tree_ensemble_py_.hpp
  onnx_extended/reference/c_ops/c_op_tree_ensemble_py_classifier_.hpp
  onnx_extended/reference/c_ops/c_op_tree_ensemble_regressor.py
  onnx_extended/reference/c_reference_evaluator.py
  requirements-dev.txt
  setup.py
Labels: runtime

#11 Adds action to check cmake syntax
  .github/workflows/cmakelint.yml
Labels: CI

#12 Adds wheels-windows.yml
  .github/workflows/wheels-windows.yml
  cmake/CMakeLists.txt
  setup.py
Labels: CI

#15 Splits files in subfolders
  .gitignore
  _doc/examples/plot_bench_cpu.py
  _doc/examples/plot_bench_cpu_vector_sum.py
  _doc/examples/plot_bench_cpu_vector_sum_avx_parallel.py
  _doc/examples/plot_bench_cpu_vector_sum_parallel.py
  _doc/examples/plot_bench_gpu_vector_sum_gpu.py
  _unittests/ut_validation/test_speed_metrics.py
  _unittests/ut_validation/test_vector_cuda.py
  _unittests/ut_validation/test_vector_sum.cpp
  _unittests/ut_validation/test_vector_sum.py
  cmake/CMakeLists.txt
  onnx_extended/__init__.py
  onnx_extended/reference/c_ops/c_op_conv.py
  onnx_extended/reference/c_ops/c_op_tree_ensemble_classifier.py
  onnx_extended/reference/c_ops/c_op_tree_ensemble_regressor.py
  onnx_extended/reference/c_ops/cpu/__init__.py
  onnx_extended/reference/c_ops/cpu/c_op_common.cpp
  onnx_extended/reference/c_ops/cpu/c_op_common.h
  onnx_extended/reference/c_ops/cpu/c_op_common_parallel.hpp
  onnx_extended/reference/c_ops/cpu/c_op_conv.h
  onnx_extended/reference/c_ops/cpu/c_op_conv_.cpp
  onnx_extended/reference/c_ops/cpu/c_op_conv_common.h
  onnx_extended/reference/c_ops/cpu/c_op_tree_ensemble_common_.hpp
  onnx_extended/reference/c_ops/cpu/c_op_tree_ensemble_common_agg_.hpp
  onnx_extended/reference/c_ops/cpu/c_op_tree_ensemble_common_classifier_.hpp
  onnx_extended/reference/c_ops/cpu/c_op_tree_ensemble_py_.cpp
  onnx_extended/reference/c_ops/cpu/c_op_tree_ensemble_py_.hpp
  onnx_extended/reference/c_ops/cpu/c_op_tree_ensemble_py_classifier_.hpp
  onnx_extended/validation/cpu/__init__.py
  onnx_extended/validation/cpu/_validation.cpp
  onnx_extended/validation/cpu/speed_metrics.cpp
  onnx_extended/validation/cpu/speed_metrics.h
  onnx_extended/validation/cpu/vector_function.cpp
  onnx_extended/validation/cpu/vector_function.h
  onnx_extended/validation/cpu/vector_sum.cpp
  onnx_extended/validation/cpu/vector_sum.h
  onnx_extended/validation/cuda/__init__.py
  onnx_extended/validation/cuda/cuda_example.cpp
  onnx_extended/validation/cuda/cuda_example.cu
  onnx_extended/validation/cuda/cuda_example.cuh
  onnx_extended/validation/cuda/cuda_example.h
  onnx_extended/validation/cuda/cuda_example_py.cpp
  onnx_extended/validation/cuda/cuda_utils.h
  onnx_extended/validation/cython/__init__.py
  onnx_extended/validation/cython/vector_function_cy.pyx
  setup.py
Labels: refactoring

#17 Add another implementation of vector sum
  README.rst
  _doc/_static/vector_sum6.png
  _doc/_static/vector_sum6_results.png
  _doc/api/reference.rst
  _doc/api/validation.rst
  _doc/examples/plot_bench_gpu_vector_sum_gpu.py
  _doc/tutorial/index.rst
  _unittests/ut_validation/test_vector_cuda.py
  azure-pipelines.yml
  clang_format.sh
  cmake/CMakeLists.txt
  cmake/CPM.cmake
  cmake/FindCudaExtension.cmake
  onnx_extended/validation/cuda/cuda_example.cu
  onnx_extended/validation/cuda/cuda_example.cuh
  onnx_extended/validation/cuda/cuda_example_py.cpp
  onnx_extended/validation/cuda/cuda_example_reduce.cu
  onnx_extended/validation/cuda/cuda_example_reduce.cuh
  onnx_extended/validation/cuda/cuda_nvtx.cuh
  setup.py
Labels: cuda

#18 Adds action for the documentation
  .github/workflows/cmakelint.yml
  .github/workflows/documentation.yml
  .github/workflows/wheels.yml
  _doc/examples/plot_bench_cpu_vector_sum_parallel.py
  _doc/index.rst
  requirements-dev.txt
Labels: CI
