Repository sdpython/onnx-extended, pull requests merged in 2023-06, with the labels that each got.

#33 Add RST Checker
  .github/workflows/rstcheck.yml
  _doc/index.rst
  azure-pipelines.yml
  pyproject.toml
  requirements-dev.txt
Labels: CI

#31 Implements a custom CUDA kernel
  .github/workflows/cmakelint.yml
  CHANGELOGS.rst
  _cmake/CMakeLists.txt
  _cmake/constants.cmake
  _cmake/externals/FindCudaExtension.cmake
  _cmake/externals/FindCython.cmake
  _cmake/externals/FindLocalEigen.cmake
  _cmake/externals/FindLocalPyBind11.cmake
  _cmake/externals/FindOrt.cmake
  _cmake/load_externals.cmake
  _cmake/targets/_validation.cmake
  _cmake/targets/cuda_example_py.cmake
  _cmake/targets/ortinf.cmake
  _cmake/targets/ortops_tutorial_cpu.cmake
  _cmake/targets/ortops_tutorial_cuda.cmake
  _doc/conf.py
  _doc/examples/plot_bench_gemm.py
  _doc/examples/plot_bench_gemm_f8.py
  _doc/tutorial/build_cuda.rst
  _doc/tutorial/build_ortext.rst
  _doc/tutorial/index.rst
  _doc/tutorial/install_cuda_wsl.rst
  _doc/tutorial/usefulcmd.rst
  _unittests/ut_ortcy/test_inference.cpp
  _unittests/ut_ortops/test_tutorial_cpu.py
  _unittests/ut_ortops/test_tutorial_cuda.py
  _unittests/ut_validation/test_cuda_gemm.py
  _unittests/ut_validation/test_vector_cuda.py
  onnx_extended/ortcy/wrap/helpers.h
  onnx_extended/ortops/__init__.py
  onnx_extended/ortops/common/common_kernels.h
  onnx_extended/ortops/common/common_kernels_cuda.h
  onnx_extended/ortops/tutorial/cpu/__init__.py
  onnx_extended/ortops/tutorial/cpu/common_kernels.h
  onnx_extended/ortops/tutorial/cpu/my_kernel.h
  onnx_extended/ortops/tutorial/cpu/my_kernel_attr.cc
  onnx_extended/ortops/tutorial/cpu/my_kernel_attr.h
  onnx_extended/ortops/tutorial/cuda/__init__.py
  onnx_extended/ortops/tutorial/cuda/custom_gemm.cu
  onnx_extended/ortops/tutorial/cuda/custom_gemm.h
  onnx_extended/ortops/tutorial/cuda/ort_tutorial_cuda_lib.cc
  onnx_extended/ortops/tutorial/cuda/ort_tutorial_cuda_lib.h
  onnx_extended/validation/cuda/cuda_example_py.cpp
  onnx_extended/validation/cuda/cuda_gemm.cu
  onnx_extended/validation/cuda/cuda_gemm.cuh
  onnx_extended/validation/cuda/cuda_tensor.cu
  onnx_extended/validation/cuda/cuda_tensor.cuh
  onnx_extended/validation/cuda/cuda_utils.h
  requirements-dev.txt
  setup.py
Labels: documentation

#34 Update onnxruntime to v1.15.1
  CHANGELOGS.rst
  _cmake/externals/FindOrt.cmake
  setup.py
Labels: CI

#35 Fixes implementation of operator CustomGemmFloat8E4M3FN
  _doc/examples/plot_bench_gemm_ort.py
  _unittests/ut_ortops/test_tutorial_cuda.py
  onnx_extended/ortops/common/common_kernels.h
  onnx_extended/ortops/common/common_kernels_cuda.h
  onnx_extended/ortops/tutorial/cuda/custom_gemm.cu
  onnx_extended/ortops/tutorial/cuda/custom_gemm.h
  onnx_extended/validation/cuda/cuda_example_py.cpp
  onnx_extended/validation/cuda/cuda_gemm.cu
Labels: operators

#36 Support Float16 in gemm benchmark
  _doc/examples/plot_bench_gemm_f8.py
  _doc/examples/plot_bench_gemm_ort.py
  _doc/examples/plot_conv.py
  _unittests/ut_ortops/test_tutorial_cuda.py
  _unittests/ut_reference/test_c_reference_evaluator.py
  _unittests/ut_validation/test_cuda_gemm.py
  _unittests/ut_xrun_doc/test_documentation_examples.py
  onnx_extended/ortops/common/common_kernels_cuda.h
  onnx_extended/ortops/tutorial/cuda/custom_gemm.cu
  onnx_extended/ortops/tutorial/cuda/custom_gemm.h
  onnx_extended/ortops/tutorial/cuda/ort_tutorial_cuda_lib.cc
  onnx_extended/validation/cuda/cuda_gemm.cu
  onnx_extended/validation/cuda/cuda_gemm.cuh
  setup.py
Labels: cuda
